import { useEffect, useState } from 'react';
import { Gift as GiftIcon, RefreshCw } from 'lucide-react';
import { cancelGift, fetchGifts, GiftError, reserveGift, type Gift, type Reservation } from '../services/gifts';

export function GiftCatalog({token,eventId,eventName}:{token:string;eventId:string;eventName:string}){
 const [gifts,setGifts]=useState<Gift[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState(false);const [revision,setRevision]=useState(0);const [busy,setBusy]=useState<string|null>(null);const [feedback,setFeedback]=useState<string|null>(null);
 const [reservations,setReservations]=useState<Record<string,Reservation>>({});
 useEffect(()=>{const controller=new AbortController();setLoading(true);setError(false);fetchGifts(token,eventId,controller.signal).then(setGifts).catch(()=>{if(!controller.signal.aborted)setError(true)}).finally(()=>{if(!controller.signal.aborted)setLoading(false)});return()=>controller.abort()},[token,eventId,revision]);
 async function refresh(){setRevision(n=>n+1)}
 async function reserve(gift:Gift){if(busy||gift.available_quantity<=0)return;setBusy(gift.gift_id);setFeedback(null);try{const result=await reserveGift(token,gift.gift_id);setReservations(prev=>({...prev,[gift.gift_id]:result}));setFeedback('Presente reservado! Guarde o número da reserva: '+result.reservation_id);await refresh()}catch(e){setFeedback(e instanceof GiftError&&e.kind==='unavailable'?'Este presente não está mais disponível. Atualize a lista.':'Não foi possível reservar. Confira sua conexão e tente novamente.')}finally{setBusy(null)}}
 async function cancel(gift:Gift){const reservation=reservations[gift.gift_id];if(!reservation||busy)return;setBusy(gift.gift_id);setFeedback(null);try{await cancelGift(token,reservation.reservation_id);setReservations(prev=>{const next={...prev};delete next[gift.gift_id];return next});setFeedback('Reserva cancelada com sucesso.');await refresh()}catch{setFeedback('Não foi possível cancelar a reserva. Tente novamente.')}finally{setBusy(null)}}
 return <section className="mt-7 rounded-xl border border-[#e9e1d5] p-5 sm:p-7"><div className="flex items-center gap-2"><GiftIcon size={19} className="text-[#aa8a60]"/><h4 className="text-xl">Presentes — {eventName}</h4></div><p className="sans mt-2 text-xs text-[#756d61]">A reserva não exige pagamento. A identidade de quem reserva não é exibida no catálogo.</p><p className="sans mt-2 text-xs text-[#756d61]">Para cancelar, utilize o botão apresentado após a reserva. Ele ficará disponível apenas nesta página enquanto ela permanecer aberta.</p><div aria-live="polite" className="sans mt-3 text-sm text-[#675d50]">{feedback}</div>{loading?<p role="status" className="sans mt-5 text-sm">Carregando presentes...</p>:error?<div className="sans mt-5 text-sm">Não foi possível carregar os presentes. <button className="underline" onClick={()=>void refresh()}>Tentar novamente</button></div>:gifts.length===0?<p className="sans mt-5 text-sm">Ainda não há presentes disponíveis para este evento.</p>:<div className="mt-5 grid gap-4 sm:grid-cols-2">{gifts.map(gift=><article key={gift.gift_id} className="rounded-xl border border-[#eee6da] bg-[#fdfbf7] p-4"><div className="flex h-28 items-center justify-center rounded-lg bg-[#f0e9df]"><GiftIcon size={36} strokeWidth={1} className="text-[#b19b7a]"/></div><h5 className="mt-4 text-lg">{gift.name}</h5>{gift.category_name&&<p className="sans mt-1 text-xs text-[#8c806f]">{gift.category_name}</p>}{gift.description&&<p className="sans mt-2 text-sm text-[#5f5b54]">{gift.description}</p>}<p className="sans mt-3 text-sm">Disponíveis: {gift.available_quantity} de {gift.quantity}</p>{reservations[gift.gift_id]?<button disabled={busy!==null} onClick={()=>void cancel(gift)} className="sans mt-4 w-full rounded-full border border-[#bca88b] px-4 py-3 text-sm disabled:opacity-50">Cancelar minha reserva</button>:<button disabled={busy!==null||gift.available_quantity<=0} onClick={()=>void reserve(gift)} className="sans mt-4 w-full rounded-full bg-[#40382e] px-4 py-3 text-sm text-white disabled:opacity-45">{busy===gift.gift_id?'Aguarde...':gift.available_quantity<=0?'Esgotado':'Reservar presente'}</button>}</article>)}</div>}<button onClick={()=>void refresh()} className="sans mt-5 inline-flex items-center gap-2 text-xs underline"><RefreshCw size={14}/>Atualizar disponibilidade</button></section>
}
