import { useEffect, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { CalendarDays, MapPin, Heart, RefreshCw } from 'lucide-react';
import { fetchInvitation, InvitationError } from '../services/invitations';
import type { InvitationContext, InvitationEvent } from '../types/invitation';
import { RsvpCard } from '../components/RsvpCard';
import { GiftCatalog } from '../components/GiftCatalog';
import { PhotoGallery } from '../components/PhotoGallery';
const formatDate=(date:string)=>new Intl.DateTimeFormat('pt-BR',{dateStyle:'long',timeZone:'America/Sao_Paulo'}).format(new Date(date));
export function InvitationPage(){
 const {token}=useParams(); const [data,setData]=useState<InvitationContext|null>(null); const [error,setError]=useState<'not-found'|'network'|null>(null); const [loading,setLoading]=useState(true); const [attempt,setAttempt]=useState(0);
 useEffect(()=>{const controller=new AbortController();setLoading(true);setError(null);setData(null);if(!token){setError('not-found');setLoading(false);return()=>controller.abort()};fetchInvitation(token,controller.signal).then(setData).catch((err:unknown)=>{if(!controller.signal.aborted)setError(err instanceof InvitationError?err.kind:'network')}).finally(()=>{if(!controller.signal.aborted)setLoading(false)});return()=>controller.abort()},[token,attempt]);
 const events=new Map<string,InvitationEvent>();data?.guests.forEach(guest=>guest.events.forEach(event=>events.set(event.id,event)));
 return <main className="min-h-screen px-5 py-12 sm:py-20"><div className="mx-auto max-w-3xl"><header className="text-center"><Link to="/" className="text-sm tracking-[.25em] uppercase text-[#9c8566] sans">Love, Lopes & Caponi</Link><div className="mx-auto my-7 h-px w-16 bg-[#c4a981]"/><p className="sans text-xs uppercase tracking-[.35em] text-[#9c8566]">Um convite especial</p><h1 className="mt-5 text-4xl sm:text-6xl leading-tight">Celebre o amor conosco</h1></header>
 <section aria-live="polite" className="mt-12 rounded-2xl border border-[#e9e1d5] bg-white/80 p-7 shadow-sm sm:p-12">
 {loading?<p role="status" className="text-center sans text-[#746e66]">Carregando seu convite...</p>:error?<div className="text-center"><h2 className="text-2xl">{error==='not-found'?'Convite não encontrado':'Não foi possível carregar seu convite'}</h2><p className="mt-3 sans text-sm text-[#746e66]">{error==='not-found'?'Confira o link recebido e tente novamente.':'Verifique sua conexão e tente novamente.'}</p>{error==='network'&&<button onClick={()=>setAttempt(n=>n+1)} className="sans mt-6 inline-flex items-center gap-2 rounded-full bg-[#40382e] px-6 py-3 text-white"><RefreshCw size={16}/>Tentar novamente</button>}</div>:data&&<><div className="text-center"><Heart size={24} strokeWidth={1.2} className="mx-auto text-[#b5966c]"/><p className="sans mt-5 text-xs uppercase tracking-widest text-[#93836e]">Preparado especialmente para</p><h2 className="mt-3 text-3xl">{data.display_name}</h2></div><div className="my-9 h-px bg-[#eee6da]"/><h3 className="text-xl">Pessoas convidadas</h3><ul className="sans mt-4 space-y-2 text-[#5f5b54]">{data.guests.map(g=><li key={g.id}>{g.name}</li>)}</ul><h3 className="mt-10 text-xl">Celebrações</h3>{events.size===0?<p className="sans mt-4 text-sm text-[#746e66]">Nenhum evento disponível para este convite.</p>:<div className="mt-5 grid gap-4">{[...events.values()].sort((a,b)=>a.event_date.localeCompare(b.event_date)).map(event=><article key={event.id} className="rounded-xl border border-[#e9e1d5] p-5"><h4 className="text-xl">{event.name}</h4><p className="sans mt-3 flex items-center gap-2 text-sm text-[#5f5b54]"><CalendarDays size={16}/>{formatDate(event.event_date)}</p>{event.venue_name&&<p className="sans mt-2 flex items-center gap-2 text-sm text-[#5f5b54]"><MapPin size={16}/>{event.venue_name}</p>}{event.address&&<p className="sans mt-2 text-sm text-[#5f5b54]">{event.address}</p>}</article>)}</div>}<div className="my-9 h-px bg-[#eee6da]"/><h3 className="text-2xl">Confirmação de presença</h3><p className="sans mt-2 text-sm text-[#756d61]">Cada pessoa pode responder individualmente para cada celebração.</p><div className="mt-6 space-y-6">{data.guests.map(guest=><section key={guest.id} className="space-y-3"><h4 className="text-xl">{guest.name}</h4>{guest.events.length===0?<p className="sans text-sm text-[#756d61]">Nenhum evento disponível.</p>:guest.events.map(event=><RsvpCard key={event.id} token={token!} guestId={guest.id} event={event}/>)}</section>)}</div><div className="my-9 h-px bg-[#eee6da]"/><h3 className="text-2xl">Lista de presentes</h3><p className="sans mt-2 text-sm text-[#756d61]">Escolha uma celebração para conhecer os presentes disponíveis.</p>{[...events.values()].sort((a,b)=>a.event_date.localeCompare(b.event_date)).map(event=><GiftCatalog key={event.id} token={token!} eventId={event.id} eventName={event.name}/>)}<PhotoGallery eventIds={[...events.keys()]}/></>}
 </section><footer className="sans mt-10 text-center text-xs tracking-widest text-[#a29a90]">COM CARINHO, LOVE, LOPES & CAPONI</footer></div></main>
}
