import { useEffect, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { CalendarDays, MapPin, Heart, RefreshCw } from 'lucide-react';
import { fetchInvitation, InvitationError } from '../services/invitations';
import type { InvitationContext, InvitationEvent } from '../types/invitation';
import { RsvpCard } from '../components/RsvpCard';
import { GiftCatalog } from '../components/GiftCatalog';
import { HomePhotoCarousel } from '../components/HomePhotoCarousel';
import { useSiteContents } from '../hooks/useSiteContents';
import { contentValue } from '../services/siteContents';
const formatDate=(date:string)=>new Intl.DateTimeFormat('pt-BR',{dateStyle:'long',timeZone:'America/Sao_Paulo'}).format(new Date(date));
export function InvitationPage(){
 const content=useSiteContents();
 const {token}=useParams(); const [data,setData]=useState<InvitationContext|null>(null); const [error,setError]=useState<'not-found'|'network'|null>(null); const [loading,setLoading]=useState(true); const [attempt,setAttempt]=useState(0);
 useEffect(()=>{const controller=new AbortController();setLoading(true);setError(null);setData(null);if(!token){setError('not-found');setLoading(false);return()=>controller.abort()};fetchInvitation(token,controller.signal).then(setData).catch((err:unknown)=>{if(!controller.signal.aborted)setError(err instanceof InvitationError?err.kind:'network')}).finally(()=>{if(!controller.signal.aborted)setLoading(false)});return()=>controller.abort()},[token,attempt]);
 const events=new Map<string,InvitationEvent>();data?.guests.forEach(guest=>guest.events.forEach(event=>events.set(event.id,event)));
 return <main className="min-h-screen overflow-x-hidden bg-[#faf8f3] px-4 py-10 sm:px-6 sm:py-16"><div className="mx-auto w-full max-w-4xl"><header className="mb-9 text-center sm:mb-12"><Link to="/" className="inline-block text-lg tracking-tight text-[#40382e] sm:text-xl">Love, Lopes <span className="text-[#b5966c]">&amp;</span> Caponi</Link></header>
 <section className="mx-auto mb-8 max-w-3xl text-center sm:mb-12">
  <div className="mb-5 flex items-center justify-center gap-4 text-[#b5966c]"><span className="h-px w-12 bg-[#c7ad87]"/><Heart size={23} strokeWidth={1.25}/><span className="h-px w-12 bg-[#c7ad87]"/></div>
  <p className="sans text-xs font-medium uppercase tracking-[.3em] text-[#8a7457]">{contentValue(content,"home.eyebrow")}</p>
  
  <div className="mx-auto my-6 h-px w-24 bg-[#c7ad87]"/>
  <p className="mx-auto max-w-xl text-lg leading-relaxed text-[#655d53] sm:text-xl">{contentValue(content,"home.subtitle")}</p>
 </section>
 <div className="-mx-4 sm:-mx-6"><HomePhotoCarousel showHeading={false}/></div>
 <div className="mb-8 text-center sm:mb-12"><div className="mx-auto mb-7 h-px w-16 bg-[#c4a981]"/><p className="sans text-xs uppercase tracking-[.35em] text-[#9c8566]">{contentValue(content,"invitation.eyebrow")}</p><h2 className="mx-auto mt-5 max-w-3xl text-[clamp(2.5rem,8vw,4.5rem)] leading-[1.12] tracking-tight text-[#40382e]">{contentValue(content,"invitation.title")}</h2></div>
 <section aria-live="polite" className="mt-9 min-w-0 rounded-2xl border border-[#e9e1d5] bg-white/85 p-5 shadow-[0_20px_70px_-55px_rgba(64,56,46,.35)] sm:mt-12 sm:p-10 lg:p-12">
 {loading?<p role="status" className="text-center sans text-[#746e66]">Carregando seu convite...</p>:error?<div className="text-center"><h2 className="text-2xl">{error==='not-found'?'Convite não encontrado':'Não foi possível carregar seu convite'}</h2><p className="mt-3 sans text-sm text-[#746e66]">{error==='not-found'?'Confira o link recebido e tente novamente.':'Verifique sua conexão e tente novamente.'}</p>{error==='network'&&<button onClick={()=>setAttempt(n=>n+1)} className="sans mt-6 inline-flex items-center gap-2 rounded-full bg-[#40382e] px-6 py-3 text-white"><RefreshCw size={16}/>Tentar novamente</button>}</div>:data&&<><div className="text-center"><Heart size={24} strokeWidth={1.2} className="mx-auto text-[#b5966c]"/><p className="sans mt-5 text-xs uppercase tracking-widest text-[#93836e]">Preparado especialmente para</p><h2 className="mt-3 text-[clamp(1.65rem,6vw,2.25rem)] leading-tight">{data.display_name}</h2></div><div className="my-9 h-px bg-[#eee6da]"/><h3 className="text-xl">Pessoas convidadas</h3><ul className="sans mt-4 space-y-2 text-[#5f5b54]">{data.guests.map(g=><li key={g.id}>{g.name}</li>)}</ul><h3 className="mt-10 text-2xl">Celebrações</h3>{events.size===0?<p className="sans mt-4 text-sm text-[#746e66]">Nenhum evento disponível para este convite.</p>:<div className="mt-5 grid gap-4 md:grid-cols-2">{[...events.values()].sort((a,b)=>a.event_date.localeCompare(b.event_date)).map(event=><article key={event.id} className="min-w-0 rounded-xl border border-[#e9e1d5] bg-[#fdfbf7] p-5"><h4 className="text-xl">{event.name}</h4><p className="sans mt-3 flex items-start gap-2 text-sm leading-relaxed text-[#5f5b54]"><CalendarDays size={16}/>{formatDate(event.event_date)}</p>{event.venue_name&&<p className="sans mt-2 flex items-start gap-2 text-sm leading-relaxed text-[#5f5b54]"><MapPin size={16}/>{event.venue_name}</p>}{event.address&&<p className="sans mt-2 text-sm text-[#5f5b54]">{event.address}</p>}</article>)}</div>}<div className="my-9 h-px bg-[#eee6da]"/><h3 className="text-2xl">Confirmação de presença</h3><p className="sans mt-2 text-sm text-[#756d61]">{contentValue(content,"invitation.rsvp_intro")}</p><div className="mt-6 space-y-6">{data.guests.map(guest=><section key={guest.id} className="min-w-0 space-y-3"><h4 className="text-xl">{guest.name}</h4>{guest.events.length===0?<p className="sans text-sm text-[#756d61]">Nenhum evento disponível.</p>:guest.events.map(event=><RsvpCard key={event.id} token={token!} guestId={guest.id} event={event}/>)}</section>)}</div><div className="my-9 h-px bg-[#eee6da]"/><h3 className="text-2xl">Lista de presentes</h3><p className="sans mt-2 text-sm text-[#756d61]">{contentValue(content,"invitation.gifts_intro")}</p>{[...events.values()].sort((a,b)=>a.event_date.localeCompare(b.event_date)).map(event=><GiftCatalog key={event.id} token={token!} eventId={event.id} eventName={event.name}/>)}</>}
 </section><footer className="sans mt-10 text-center text-xs tracking-widest text-[#a29a90]">{contentValue(content,"invitation.footer")}</footer></div></main>
}
